service:
  name: cautious-waffle
# app and org for use with dashboard.serverless.com
app: my-first-app
org: shindakun

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  regiion: us-west-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SLACK_SIGNATURE: ${param:slack_signature}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  waffle:
    handler: handler.slack
    events:
      - http:
          method: post
          path: slack
