service:
  name: cautious-waffle
# app and org for use with dashboard.serverless.com
app: my-first-app
org: shindakun

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: characters
            sources: [./offline/migrations/characters.json]

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  regiion: us-west-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:*"
    Resource:
      - "arn:aws:dynamodb:*:*"
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  waffle:
    handler: handler.slack
    events:
      - http:
          method: post
          path: slack
  character:
    handler: handler.dyno
    events:
      - http:
          method: get
          path: dyno

resources:
  Resources:
    charactersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy : Retain
      Properties:
        TableName: characters
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**